### PR TITLE
[IAP]Update the example for IAP extension.

### PR DESCRIPTION
**Pull request by minggangw**
As the IAP extension has been refactored, updating this example to
combine with the new JS interfaces. Also, using app-tools to pack the
apk file.

BUG=XWALK-5696,5697

### CODE REVIEW

**Comment by minggangw** [comment]
@halton @jondong please review the PR, thanks!

**Comment by jondong** [comment]
while you need to fix the failed to build issue firstly.

**Comment by minggangw** [comment]
As the .travis.yml hasn't been merged, the Travis-CI reports "Could not find .travis.yml.". It'll be OK after the .travis.yml is committed. We could re-check after PR#31 is merged.

**Comment by halton** [comment]
@minggangw please re-trigger the trybot, if it passed, I'll merge this PR

**Comment by halton** [comment]
Turn out I can restart the tybot, but still fail.

```
$ rake
rake aborted!
No Rakefile found (looking for: rakefile, Rakefile, rakefile.rb, Rakefile.rb)
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `eval'
/home/travis/.rvm/gems/ruby-1.9.3-p551/bin/ruby_executable_hooks:15:in `<main>'
(See full trace by running task with --trace)
The command "rake" exited with 1.
```

**Pull request merged**
